# Deploy to Kubernetes - Review app with Azure DevSpaces
# Build and push image to Azure Container Registry; Deploy to Azure Kuberentes Services and setup Review App with Azure DevSpaces
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '36a19b79-1aab-4594-8dc3-dfda8383456d'
  imageRepository: 'dockersamplenginx'
  containerRegistry: 'demo1555.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'demo15551478cc91-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Azure Service connection
  azureConnection: '73edf893-eb36-4b6b-9e06-c66287432ed1'

  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
- stage: Deploy
  displayName: Deploy stage
  # dependsOn: Build

  jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
              action: deploy
              kubernetesServiceConnection: k8s-demo
              namespace: test2
              manifests: |
                ubuntu.yaml
                nginx.yaml

